# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号码')),
                ('name', models.CharField(default='', max_length=20, verbose_name='昵称')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('sex', models.SmallIntegerField(choices=[(1, '男'), (2, '女'), (3, '保密')], default=3, verbose_name='性别')),
                ('school', models.CharField(default='', max_length=50, verbose_name='学校')),
                ('hometown', models.CharField(default='', max_length=100, verbose_name='家乡')),
                ('address', models.CharField(default='', max_length=255, verbose_name='详细地址')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
