# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180924_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='head',
            field=models.ImageField(default='user/201809/24/IMG_2938.JPG', upload_to='head/%Y/%m', verbose_name='用户头像'),
        ),
    ]
